### Exercise 14: Create some array and dictionary to create Pandas series

In [1]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


### Exercise 15: Creating a Pandas Series

In [2]:
s1=pd.Series(data=my_data)
s1

0    10
1    20
2    30
dtype: int64

In [7]:
s1=pd.DataFrame(data=my_data,index=['a','b','c'])
#s1=pd.DataFrame(data=my_data)

In [8]:
s1

0
a  10
b  20
c  30

In [5]:
arr

array([10, 20, 30])

In [10]:
# pandas axis=0 is rows, axis=1 is columns
s1.drop('a',axis = 0)


0
b  20
c  30

In [16]:
s2=pd.Series(data=[10,20,30], index=['a','b','c'])
print(s2)

    0
a  10
b  20
c  30


In [ ]:
s2["b"]

In [19]:
s2=pd.DataFrame(data=my_data, index=labels)
s2.loc["b"]

0    20
Name: b, dtype: int64

In [23]:
s3=pd.Series(arr, labels)
print(s3)

0
a  10
b  20
c  30

In [24]:
s4=pd.Series(d)
print(s4)

a    10
b    20
c    30
dtype: int64


### Exercise 16: Pandas series can hold many types of data

In [25]:
print ("\nHolding numerical data\n",'-'*25, sep='')
print(pd.Series(arr))
print ("\nHolding text labels\n",'-'*20, sep='')
print(pd.Series(labels))
print ("\nHolding functions\n",'-'*20, sep='')
print(pd.Series(data=[sum,print,len]))
print ("\nHolding objects from a dictionary\n",'-'*40, sep='')
print(pd.Series(data=[d.keys, d.items, d.values]))


Holding numerical data
-------------------------
0    10
1    20
2    30
dtype: int32

Holding text labels
--------------------
0    a
1    b
2    c
dtype: object

Holding functions
--------------------
0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

Holding objects from a dictionary
----------------------------------------
0    <built-in method keys of dict object at 0x0000...
1    <built-in method items of dict object at 0x000...
2    <built-in method values of dict object at 0x00...
dtype: object


In [ ]:
pd2 = pd.Series(data=[d.keys, d.items, d.values])
pd2           

### Exercise 17: Creating Pandas DataFrame

In [27]:
matrix_data = np.random.randint(1,10,size=20).reshape(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['intW','intX','intY','intZ']

df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
df


The data frame looks like
---------------------------------------------


intW  intX  intY  intZ
A     5     1     1     2
B     1     1     3     7
C     9     6     2     7
D     7     3     6     1
E     6     9     7     4

In [29]:
df.describe().T

count  mean       std  min  25%  50%  75%  max
intW    5.0   5.6  2.966479  1.0  5.0  6.0  7.0  9.0
intX    5.0   4.0  3.464102  1.0  1.0  3.0  6.0  9.0
intY    5.0   3.8  2.588436  1.0  2.0  3.0  6.0  7.0
intZ    5.0   4.2  2.774887  1.0  2.0  4.0  7.0  7.0

In [30]:
import pandas as pd
import numpy as np

#d={'a':[10,20],'b':[30,40],'c':[50,60]}
d=[[10,20],[30,40],[50,60]]
d_np = np.array(d).reshape(2,3)
print(d_np)
#df2=pd.DataFrame(data=d,index=['X','Y','Z'])
df2=pd.DataFrame(data=d)
print(df2)

[[10 20 30]
 [40 50 60]]
    0   1
0  10  20
1  30  40
2  50  60


In [31]:
df3=pd.DataFrame(data=d_np)
print(df3)

    0   1   2
0  10  20  30
1  40  50  60


### Exercise 18: Viewing a DataFrame partially

In [32]:
# 25 rows and 4 columns
matrix_data = np.random.randint(1,100,100).reshape(25,4)
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(data=matrix_data,columns=column_headings)

In [33]:
df.head(10)

W   X   Y   Z
0  15  85  19  91
1  60  87  73  61
2   2  62  16  56
3  30  67  34  79
4  60  12  57  49
5  44  46   9  69
6  81  18  87  93
7  50  96   7  80
8  74  84  88  38
9  31  20  77   4

In [34]:
df.tail(10)

W   X   Y   Z
15  75  72   2  62
16  20  79  25   8
17  77  34  95  66
18   4  75  18  94
19  10  31  89  53
20  20  32  57  44
21   7  47  88  42
22  18   1  62  49
23  29  44  13   9
24  32  59  43  33

In [ ]:
df

### Exercise 19: Indexing and slicing (columns)

In [35]:
print("\nThe 'X' column\n",'-'*25, sep='')
print(df['X'])
print("\nType of the column: ", type(df['X']), sep='')
print("\nThe 'X' and 'Z' columns indexed by passing a list\n",'-'*55, sep='')
print(df[['X','Z']])
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')


The 'X' column
-------------------------
0     85
1     87
2     62
3     67
4     12
5     46
6     18
7     96
8     84
9     20
10    40
11    43
12    84
13    68
14    45
15    72
16    79
17    34
18    75
19    31
20    32
21    47
22     1
23    44
24    59
Name: X, dtype: int32

Type of the column: <class 'pandas.core.series.Series'>

The 'X' and 'Z' columns indexed by passing a list
-------------------------------------------------------
     X   Z
0   85  91
1   87  61
2   62  56
3   67  79
4   12  49
5   46  69
6   18  93
7   96  80
8   84  38
9   20   4
10  40  29
11  43  78
12  84  67
13  68  93
14  45  59
15  72  62
16  79   8
17  34  66
18  75  94
19  31  53
20  32  44
21  47  42
22   1  49
23  44   9
24  59  33

Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>


In [ ]:
df.drop('W',axis = 1)

### Exercise 20: Indexing and slicing (rows)

In [36]:
matrix_data = np.random.randint(1,10,size=20).reshape(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.loc['C'])
print("\nMultiple rows\n")
print(df.loc[['B','C']])
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W    3
X    3
Y    4
Z    3
Name: C, dtype: int32

Multiple rows

   W  X  Y  Z
B  8  3  3  2
C  3  3  4  3

Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W    3
X    3
Y    4
Z    3
Name: C, dtype: int32

Multiple rows

   W  X  Y  Z
B  8  3  3  2
C  3  3  4  3


In [39]:
df.loc[["C"],["Y"]]

Y
C  4

In [37]:
df.iloc[2]

W    3
X    3
Y    4
Z    3
Name: C, dtype: int32

### Exercise 21: Creating and deleting a (new) column (or row)

In [40]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep='')
df = df.drop('New', axis=1) # Notice the axis=1 option, axis = 0 is default, so one has to change it to 1
print(df)
df1=df.drop('A')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df2 = df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df2)


A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
   W  X  Y  Z  New  New (Sum of X and Z)
A  7  4  6  6   10                    10
B  8  3  3  2    5                     5
C  3  3  4  3    6                     6
D  9  1  4  5    6                     6
E  8  8  9  4   12                    12

A column is dropped by using df.drop() method
-------------------------------------------------------
   W  X  Y  Z  New (Sum of X and Z)
A  7  4  6  6                    10
B  8  3  3  2                     5
C  3  3  4  3                     6
D  9  1  4  5                     6
E  8  8  9  4                    12

A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
   W  X  Y  Z  New (Sum of X and Z)
B  8  3  3  2                     5
C  3  3  4  3                     6
D  9  1  4  5                     6
E  8  8  9  4  

In [41]:
df

W  X  Y  Z
A  7  4  6  6
B  8  3  3  2
C  3  3  4  3
D  9  1  4  5
E  8  8  9  4

In [42]:
df.to_csv('mighty_data.csv')

In [43]:
!head mighty_data.csv

,W,X,Y,Z
A,7,4,6,6
B,8,3,3,2
C,3,3,4,3
D,9,1,4,5
E,8,8,9,4


In [54]:
df2 = pd.read_csv('mighty_data.csv')
df2

Unnamed: 0  W  X  Y  Z
0          A  7  4  6  6
1          B  8  3  3  2
2          C  3  3  4  3
3          D  9  1  4  5
4          E  8  8  9  4

In [57]:
df2.set_index("Unnamed: 0",inplace=True )
df2

W  X  Y  Z
Unnamed: 0            
A           7  4  6  6
B           8  3  3  2
C           3  3  4  3
D           9  1  4  5
E           8  8  9  4

In [ ]:
!ls

In [ ]:
df_new = pd.read_csv('mighty_data.csv')
df_new.to_csv('mighty_data_copy.csv')